#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
HOST="${HOST:-127.0.0.1}"
PORT="${PORT:-29001}"
DURATION="${DURATION:-300}"
TARGET_RPS="${TARGET_RPS:-10000}"
TARGET_COMPLETED_RPS="${TARGET_COMPLETED_RPS:-10000}"
TARGET_ACK_P99_US="${TARGET_ACK_P99_US:-100}"
TARGET_ACK_ACCEPTED_P99_US="${TARGET_ACK_ACCEPTED_P99_US:-40}"
TARGET_ACCEPTED_RATE="${TARGET_ACCEPTED_RATE:-0.99}"
DURABLE_TAIL_STAGE="${DURABLE_TAIL_STAGE:-1}"
if [[ -z "${TARGET_DURABLE_CONFIRM_P99_US:-}" ]]; then
  case "$DURABLE_TAIL_STAGE" in
    0) TARGET_DURABLE_CONFIRM_P99_US=0 ;;
    1) TARGET_DURABLE_CONFIRM_P99_US=120000000 ;;
    2) TARGET_DURABLE_CONFIRM_P99_US=60000000 ;;
    3) TARGET_DURABLE_CONFIRM_P99_US=20000000 ;;
    4) TARGET_DURABLE_CONFIRM_P99_US=5000000 ;;
    *) echo "FAIL: invalid DURABLE_TAIL_STAGE=$DURABLE_TAIL_STAGE (expected 0..4)"; exit 1 ;;
  esac
fi
WARN_DURABLE_CONFIRM_P99_US="${WARN_DURABLE_CONFIRM_P99_US:-120000000}"
TARGET_REJECTED_KILLED_MAX="${TARGET_REJECTED_KILLED_MAX:-0}"
TARGET_LOSS_SUSPECT_MAX="${TARGET_LOSS_SUSPECT_MAX:-0}"
TARGET_OFFERED_RPS_RATIO_MIN="${TARGET_OFFERED_RPS_RATIO_MIN:-0.99}"
TARGET_DROPPED_OFFER_RATIO_MAX="${TARGET_DROPPED_OFFER_RATIO_MAX:-0.001}"
TARGET_UNSENT_TOTAL_MAX="${TARGET_UNSENT_TOTAL_MAX:-0}"
TARGET_STRICT_LANE_TOPOLOGY="${TARGET_STRICT_LANE_TOPOLOGY:-1}"
V3_INGRESS_TRANSPORT="${V3_INGRESS_TRANSPORT:-tcp}"
V3_TCP_PORT="${V3_TCP_PORT:-39001}"
LOAD_WORKERS="${LOAD_WORKERS:-192}"
LOAD_ACCOUNTS="${LOAD_ACCOUNTS:-24}"
LOAD_QUEUE_CAPACITY="${LOAD_QUEUE_CAPACITY:-200000}"
LOAD_FINAL_CATCHUP="${LOAD_FINAL_CATCHUP:-true}"
REQUEST_TIMEOUT_SEC="${REQUEST_TIMEOUT_SEC:-2}"
DRAIN_TIMEOUT_SEC="${DRAIN_TIMEOUT_SEC:-30}"
BUILD_RELEASE="${BUILD_RELEASE:-0}"
OUT_DIR="${OUT_DIR:-$ROOT_DIR/var/results}"

# Recommended local profile (Darwin/Linux single-node reproducibility).
V3_SOFT_REJECT_PCT="${V3_SOFT_REJECT_PCT:-85}"
V3_HARD_REJECT_PCT="${V3_HARD_REJECT_PCT:-92}"
V3_KILL_REJECT_PCT="${V3_KILL_REJECT_PCT:-98}"
V3_KILL_AUTO_RECOVER="${V3_KILL_AUTO_RECOVER:-false}"
V3_INGRESS_QUEUE_CAPACITY="${V3_INGRESS_QUEUE_CAPACITY:-131072}"
V3_DURABILITY_QUEUE_CAPACITY="${V3_DURABILITY_QUEUE_CAPACITY:-4000000}"
V3_SHARD_COUNT="${V3_SHARD_COUNT:-8}"
V3_LOSS_GAP_TIMEOUT_MS="${V3_LOSS_GAP_TIMEOUT_MS:-360000}"
V3_SESSION_LOSS_SUSPECT_THRESHOLD="${V3_SESSION_LOSS_SUSPECT_THRESHOLD:-4096}"
V3_SHARD_LOSS_SUSPECT_THRESHOLD="${V3_SHARD_LOSS_SUSPECT_THRESHOLD:-32768}"
V3_GLOBAL_LOSS_SUSPECT_THRESHOLD="${V3_GLOBAL_LOSS_SUSPECT_THRESHOLD:-131072}"
V3_DURABLE_WORKER_BATCH_MAX="${V3_DURABLE_WORKER_BATCH_MAX:-24}"
V3_DURABLE_WORKER_BATCH_MIN="${V3_DURABLE_WORKER_BATCH_MIN:-12}"
V3_DURABLE_WORKER_BATCH_WAIT_US="${V3_DURABLE_WORKER_BATCH_WAIT_US:-40}"
V3_DURABLE_WORKER_BATCH_WAIT_MIN_US="${V3_DURABLE_WORKER_BATCH_WAIT_MIN_US:-20}"
V3_DURABLE_WORKER_RECEIPT_TIMEOUT_US="${V3_DURABLE_WORKER_RECEIPT_TIMEOUT_US:-20000000}"
V3_DURABLE_WORKER_MAX_INFLIGHT_RECEIPTS="${V3_DURABLE_WORKER_MAX_INFLIGHT_RECEIPTS:-49152}"
V3_DURABLE_WORKER_INFLIGHT_SOFT_CAP_PCT="${V3_DURABLE_WORKER_INFLIGHT_SOFT_CAP_PCT:-50}"
V3_DURABLE_WORKER_INFLIGHT_HARD_CAP_PCT="${V3_DURABLE_WORKER_INFLIGHT_HARD_CAP_PCT:-25}"
V3_DURABLE_WORKER_BATCH_ADAPTIVE="${V3_DURABLE_WORKER_BATCH_ADAPTIVE:-false}"
V3_DURABLE_WORKER_BATCH_ADAPTIVE_LOW_UTIL_PCT="${V3_DURABLE_WORKER_BATCH_ADAPTIVE_LOW_UTIL_PCT:-10}"
V3_DURABLE_WORKER_BATCH_ADAPTIVE_HIGH_UTIL_PCT="${V3_DURABLE_WORKER_BATCH_ADAPTIVE_HIGH_UTIL_PCT:-60}"
V3_DURABLE_SOFT_REJECT_PCT="${V3_DURABLE_SOFT_REJECT_PCT:-$V3_SOFT_REJECT_PCT}"
V3_DURABLE_HARD_REJECT_PCT="${V3_DURABLE_HARD_REJECT_PCT:-$V3_HARD_REJECT_PCT}"
V3_DURABLE_BACKLOG_SIGNAL_MIN_QUEUE_PCT="${V3_DURABLE_BACKLOG_SIGNAL_MIN_QUEUE_PCT:-30}"
V3_DURABLE_ADMISSION_FSYNC_PRESIGNAL_PCT="${V3_DURABLE_ADMISSION_FSYNC_PRESIGNAL_PCT:-1.0}"
V3_DURABLE_CONFIRM_SOFT_REJECT_AGE_US="${V3_DURABLE_CONFIRM_SOFT_REJECT_AGE_US:-0}"
V3_DURABLE_CONFIRM_HARD_REJECT_AGE_US="${V3_DURABLE_CONFIRM_HARD_REJECT_AGE_US:-0}"
FASTPATH_DRAIN_WORKERS="${FASTPATH_DRAIN_WORKERS:-4}"
AUDIT_FDATASYNC_MAX_WAIT_US="${AUDIT_FDATASYNC_MAX_WAIT_US:-150}"
AUDIT_FDATASYNC_MAX_BATCH="${AUDIT_FDATASYNC_MAX_BATCH:-64}"

cd "$ROOT_DIR"

HOST="$HOST" \
PORT="$PORT" \
DURATION="$DURATION" \
TARGET_RPS="$TARGET_RPS" \
TARGET_COMPLETED_RPS="$TARGET_COMPLETED_RPS" \
TARGET_ACK_P99_US="$TARGET_ACK_P99_US" \
TARGET_ACK_ACCEPTED_P99_US="$TARGET_ACK_ACCEPTED_P99_US" \
TARGET_ACCEPTED_RATE="$TARGET_ACCEPTED_RATE" \
TARGET_DURABLE_CONFIRM_P99_US="$TARGET_DURABLE_CONFIRM_P99_US" \
WARN_DURABLE_CONFIRM_P99_US="$WARN_DURABLE_CONFIRM_P99_US" \
TARGET_REJECTED_KILLED_MAX="$TARGET_REJECTED_KILLED_MAX" \
TARGET_LOSS_SUSPECT_MAX="$TARGET_LOSS_SUSPECT_MAX" \
TARGET_OFFERED_RPS_RATIO_MIN="$TARGET_OFFERED_RPS_RATIO_MIN" \
TARGET_DROPPED_OFFER_RATIO_MAX="$TARGET_DROPPED_OFFER_RATIO_MAX" \
TARGET_UNSENT_TOTAL_MAX="$TARGET_UNSENT_TOTAL_MAX" \
TARGET_STRICT_LANE_TOPOLOGY="$TARGET_STRICT_LANE_TOPOLOGY" \
V3_INGRESS_TRANSPORT="$V3_INGRESS_TRANSPORT" \
V3_TCP_PORT="$V3_TCP_PORT" \
LOAD_WORKERS="$LOAD_WORKERS" \
LOAD_ACCOUNTS="$LOAD_ACCOUNTS" \
LOAD_QUEUE_CAPACITY="$LOAD_QUEUE_CAPACITY" \
LOAD_FINAL_CATCHUP="$LOAD_FINAL_CATCHUP" \
REQUEST_TIMEOUT_SEC="$REQUEST_TIMEOUT_SEC" \
DRAIN_TIMEOUT_SEC="$DRAIN_TIMEOUT_SEC" \
BUILD_RELEASE="$BUILD_RELEASE" \
OUT_DIR="$OUT_DIR" \
V3_SOFT_REJECT_PCT="$V3_SOFT_REJECT_PCT" \
V3_HARD_REJECT_PCT="$V3_HARD_REJECT_PCT" \
V3_KILL_REJECT_PCT="$V3_KILL_REJECT_PCT" \
V3_KILL_AUTO_RECOVER="$V3_KILL_AUTO_RECOVER" \
V3_INGRESS_QUEUE_CAPACITY="$V3_INGRESS_QUEUE_CAPACITY" \
V3_DURABILITY_QUEUE_CAPACITY="$V3_DURABILITY_QUEUE_CAPACITY" \
V3_SHARD_COUNT="$V3_SHARD_COUNT" \
V3_LOSS_GAP_TIMEOUT_MS="$V3_LOSS_GAP_TIMEOUT_MS" \
V3_SESSION_LOSS_SUSPECT_THRESHOLD="$V3_SESSION_LOSS_SUSPECT_THRESHOLD" \
V3_SHARD_LOSS_SUSPECT_THRESHOLD="$V3_SHARD_LOSS_SUSPECT_THRESHOLD" \
V3_GLOBAL_LOSS_SUSPECT_THRESHOLD="$V3_GLOBAL_LOSS_SUSPECT_THRESHOLD" \
V3_DURABLE_WORKER_BATCH_MAX="$V3_DURABLE_WORKER_BATCH_MAX" \
V3_DURABLE_WORKER_BATCH_MIN="$V3_DURABLE_WORKER_BATCH_MIN" \
V3_DURABLE_WORKER_BATCH_WAIT_US="$V3_DURABLE_WORKER_BATCH_WAIT_US" \
V3_DURABLE_WORKER_BATCH_WAIT_MIN_US="$V3_DURABLE_WORKER_BATCH_WAIT_MIN_US" \
V3_DURABLE_WORKER_RECEIPT_TIMEOUT_US="$V3_DURABLE_WORKER_RECEIPT_TIMEOUT_US" \
V3_DURABLE_WORKER_MAX_INFLIGHT_RECEIPTS="$V3_DURABLE_WORKER_MAX_INFLIGHT_RECEIPTS" \
V3_DURABLE_WORKER_INFLIGHT_SOFT_CAP_PCT="$V3_DURABLE_WORKER_INFLIGHT_SOFT_CAP_PCT" \
V3_DURABLE_WORKER_INFLIGHT_HARD_CAP_PCT="$V3_DURABLE_WORKER_INFLIGHT_HARD_CAP_PCT" \
V3_DURABLE_WORKER_BATCH_ADAPTIVE="$V3_DURABLE_WORKER_BATCH_ADAPTIVE" \
V3_DURABLE_WORKER_BATCH_ADAPTIVE_LOW_UTIL_PCT="$V3_DURABLE_WORKER_BATCH_ADAPTIVE_LOW_UTIL_PCT" \
V3_DURABLE_WORKER_BATCH_ADAPTIVE_HIGH_UTIL_PCT="$V3_DURABLE_WORKER_BATCH_ADAPTIVE_HIGH_UTIL_PCT" \
V3_DURABLE_SOFT_REJECT_PCT="$V3_DURABLE_SOFT_REJECT_PCT" \
V3_DURABLE_HARD_REJECT_PCT="$V3_DURABLE_HARD_REJECT_PCT" \
V3_DURABLE_BACKLOG_SIGNAL_MIN_QUEUE_PCT="$V3_DURABLE_BACKLOG_SIGNAL_MIN_QUEUE_PCT" \
V3_DURABLE_ADMISSION_FSYNC_PRESIGNAL_PCT="$V3_DURABLE_ADMISSION_FSYNC_PRESIGNAL_PCT" \
V3_DURABLE_CONFIRM_SOFT_REJECT_AGE_US="$V3_DURABLE_CONFIRM_SOFT_REJECT_AGE_US" \
V3_DURABLE_CONFIRM_HARD_REJECT_AGE_US="$V3_DURABLE_CONFIRM_HARD_REJECT_AGE_US" \
FASTPATH_DRAIN_WORKERS="$FASTPATH_DRAIN_WORKERS" \
AUDIT_FDATASYNC_MAX_WAIT_US="$AUDIT_FDATASYNC_MAX_WAIT_US" \
AUDIT_FDATASYNC_MAX_BATCH="$AUDIT_FDATASYNC_MAX_BATCH" \
ENFORCE_GATE=1 \
scripts/ops/run_v3_open_loop_probe.sh
