#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"

# Durable-tail gate: tuning/validation gate, not default release gate.
DURATION="${DURATION:-120}"
TARGET_RPS="${TARGET_RPS:-10000}"
TARGET_COMPLETED_RPS="${TARGET_COMPLETED_RPS:-10000}"
TARGET_ACK_P99_US="${TARGET_ACK_P99_US:-100}"
TARGET_ACK_ACCEPTED_P99_US="${TARGET_ACK_ACCEPTED_P99_US:-40}"
TARGET_ACCEPTED_RATE="${TARGET_ACCEPTED_RATE:-0.95}"
TARGET_DURABLE_CONFIRM_P99_US="${TARGET_DURABLE_CONFIRM_P99_US:-20000000}"
TARGET_REJECTED_KILLED_MAX="${TARGET_REJECTED_KILLED_MAX:-0}"
TARGET_LOSS_SUSPECT_MAX="${TARGET_LOSS_SUSPECT_MAX:-0}"

# Tail-focused defaults.
V3_DURABLE_SOFT_REJECT_PCT="${V3_DURABLE_SOFT_REJECT_PCT:-82}"
V3_DURABLE_HARD_REJECT_PCT="${V3_DURABLE_HARD_REJECT_PCT:-90}"
V3_DURABLE_BACKLOG_SIGNAL_MIN_QUEUE_PCT="${V3_DURABLE_BACKLOG_SIGNAL_MIN_QUEUE_PCT:-80}"
V3_DURABLE_CONFIRM_SOFT_REJECT_AGE_US="${V3_DURABLE_CONFIRM_SOFT_REJECT_AGE_US:-60000000}"
V3_DURABLE_CONFIRM_HARD_REJECT_AGE_US="${V3_DURABLE_CONFIRM_HARD_REJECT_AGE_US:-180000000}"

cd "$ROOT_DIR"

DURATION="$DURATION" \
TARGET_RPS="$TARGET_RPS" \
TARGET_COMPLETED_RPS="$TARGET_COMPLETED_RPS" \
TARGET_ACK_P99_US="$TARGET_ACK_P99_US" \
TARGET_ACK_ACCEPTED_P99_US="$TARGET_ACK_ACCEPTED_P99_US" \
TARGET_ACCEPTED_RATE="$TARGET_ACCEPTED_RATE" \
TARGET_DURABLE_CONFIRM_P99_US="$TARGET_DURABLE_CONFIRM_P99_US" \
TARGET_REJECTED_KILLED_MAX="$TARGET_REJECTED_KILLED_MAX" \
TARGET_LOSS_SUSPECT_MAX="$TARGET_LOSS_SUSPECT_MAX" \
V3_DURABLE_SOFT_REJECT_PCT="$V3_DURABLE_SOFT_REJECT_PCT" \
V3_DURABLE_HARD_REJECT_PCT="$V3_DURABLE_HARD_REJECT_PCT" \
V3_DURABLE_BACKLOG_SIGNAL_MIN_QUEUE_PCT="$V3_DURABLE_BACKLOG_SIGNAL_MIN_QUEUE_PCT" \
V3_DURABLE_CONFIRM_SOFT_REJECT_AGE_US="$V3_DURABLE_CONFIRM_SOFT_REJECT_AGE_US" \
V3_DURABLE_CONFIRM_HARD_REJECT_AGE_US="$V3_DURABLE_CONFIRM_HARD_REJECT_AGE_US" \
scripts/ops/check_v3_local_strict_gate.sh
