#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
if [[ -n "${V3_OPS_PRESET:-}" ]]; then
  # shellcheck source=/dev/null
  source "$ROOT_DIR/scripts/ops/v3_preset_env.sh"
  apply_v3_ops_preset "$V3_OPS_PRESET"
fi

# Stable gate: reproducible 10k/300s line.
DURATION="${DURATION:-300}"
TARGET_RPS="${TARGET_RPS:-10000}"
TARGET_COMPLETED_RPS="${TARGET_COMPLETED_RPS:-10000}"
TARGET_ACK_P99_US="${TARGET_ACK_P99_US:-100}"
TARGET_ACK_ACCEPTED_P99_US="${TARGET_ACK_ACCEPTED_P99_US:-40}"
TARGET_ACK_ACCEPTED_P99_NS="${TARGET_ACK_ACCEPTED_P99_NS:-0}"
TARGET_ACK_ACCEPTED_TSC_P99_NS="${TARGET_ACK_ACCEPTED_TSC_P99_NS:-0}"
TARGET_ACCEPTED_RATE="${TARGET_ACCEPTED_RATE:-0.99}"
TARGET_DURABLE_CONFIRM_P99_US="${TARGET_DURABLE_CONFIRM_P99_US:-0}"
WARN_DURABLE_CONFIRM_P99_US="${WARN_DURABLE_CONFIRM_P99_US:-120000000}"
TARGET_REJECTED_KILLED_MAX="${TARGET_REJECTED_KILLED_MAX:-0}"
TARGET_LOSS_SUSPECT_MAX="${TARGET_LOSS_SUSPECT_MAX:-0}"

cd "$ROOT_DIR"

DURATION="$DURATION" \
TARGET_RPS="$TARGET_RPS" \
TARGET_COMPLETED_RPS="$TARGET_COMPLETED_RPS" \
TARGET_ACK_P99_US="$TARGET_ACK_P99_US" \
TARGET_ACK_ACCEPTED_P99_US="$TARGET_ACK_ACCEPTED_P99_US" \
TARGET_ACK_ACCEPTED_P99_NS="$TARGET_ACK_ACCEPTED_P99_NS" \
TARGET_ACK_ACCEPTED_TSC_P99_NS="$TARGET_ACK_ACCEPTED_TSC_P99_NS" \
TARGET_ACCEPTED_RATE="$TARGET_ACCEPTED_RATE" \
TARGET_DURABLE_CONFIRM_P99_US="$TARGET_DURABLE_CONFIRM_P99_US" \
WARN_DURABLE_CONFIRM_P99_US="$WARN_DURABLE_CONFIRM_P99_US" \
TARGET_REJECTED_KILLED_MAX="$TARGET_REJECTED_KILLED_MAX" \
TARGET_LOSS_SUSPECT_MAX="$TARGET_LOSS_SUSPECT_MAX" \
scripts/ops/check_v3_local_strict_gate.sh
