#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
HOST="${HOST:-127.0.0.1}"
PORT="${PORT:-29001}"
DURATION="${DURATION:-300}"
TARGET_RPS="${TARGET_RPS:-10000}"
TARGET_COMPLETED_RPS="${TARGET_COMPLETED_RPS:-10000}"
TARGET_COMPLETED_RPS_EPSILON="${TARGET_COMPLETED_RPS_EPSILON:-0.0005}"
TARGET_ACK_P99_US="${TARGET_ACK_P99_US:-100}"
TARGET_ACK_ACCEPTED_P99_US="${TARGET_ACK_ACCEPTED_P99_US:-40}"
TARGET_ACCEPTED_RATE="${TARGET_ACCEPTED_RATE:-0.99}"
DURABLE_TAIL_STAGE="${DURABLE_TAIL_STAGE:-1}"
if [[ -z "${TARGET_DURABLE_CONFIRM_P99_US:-}" ]]; then
  case "$DURABLE_TAIL_STAGE" in
    0) TARGET_DURABLE_CONFIRM_P99_US=0 ;;
    1) TARGET_DURABLE_CONFIRM_P99_US=120000000 ;;
    2) TARGET_DURABLE_CONFIRM_P99_US=60000000 ;;
    3) TARGET_DURABLE_CONFIRM_P99_US=20000000 ;;
    4) TARGET_DURABLE_CONFIRM_P99_US=5000000 ;;
    *) echo "FAIL: invalid DURABLE_TAIL_STAGE=$DURABLE_TAIL_STAGE (expected 0..4)"; exit 1 ;;
  esac
fi
WARN_DURABLE_CONFIRM_P99_US="${WARN_DURABLE_CONFIRM_P99_US:-120000000}"
TARGET_REJECTED_KILLED_MAX="${TARGET_REJECTED_KILLED_MAX:-0}"
TARGET_LOSS_SUSPECT_MAX="${TARGET_LOSS_SUSPECT_MAX:-0}"
TARGET_OFFERED_RPS_RATIO_MIN="${TARGET_OFFERED_RPS_RATIO_MIN:-0.99}"
TARGET_DROPPED_OFFER_RATIO_MAX="${TARGET_DROPPED_OFFER_RATIO_MAX:-0.001}"
TARGET_UNSENT_TOTAL_MAX="${TARGET_UNSENT_TOTAL_MAX:-0}"
TARGET_STRICT_LANE_TOPOLOGY="${TARGET_STRICT_LANE_TOPOLOGY:-1}"
TARGET_STRICT_PER_LANE_CHECKS="${TARGET_STRICT_PER_LANE_CHECKS:-1}"
TARGET_DURABLE_INFLIGHT_SKEW_RATIO_MAX="${TARGET_DURABLE_INFLIGHT_SKEW_RATIO_MAX:-3.50}"
TARGET_DURABLE_INFLIGHT_HOT_LANE_SHARE_MAX="${TARGET_DURABLE_INFLIGHT_HOT_LANE_SHARE_MAX:-0.40}"
WARN_DURABLE_INFLIGHT_SKEW_RATIO="${WARN_DURABLE_INFLIGHT_SKEW_RATIO:-2.50}"
WARN_DURABLE_INFLIGHT_HOT_LANE_SHARE="${WARN_DURABLE_INFLIGHT_HOT_LANE_SHARE:-0.30}"
RUNS="${RUNS:-1}"
MIN_PASS_RATIO="${MIN_PASS_RATIO:-1.0}"
INTERVAL_SEC="${INTERVAL_SEC:-0}"
V3_INGRESS_TRANSPORT="${V3_INGRESS_TRANSPORT:-tcp}"
V3_TCP_PORT="${V3_TCP_PORT:-39001}"
LOAD_WORKERS="${LOAD_WORKERS:-192}"
LOAD_ACCOUNTS="${LOAD_ACCOUNTS:-24}"
LOAD_QUEUE_CAPACITY="${LOAD_QUEUE_CAPACITY:-200000}"
LOAD_FINAL_CATCHUP="${LOAD_FINAL_CATCHUP:-true}"
REQUEST_TIMEOUT_SEC="${REQUEST_TIMEOUT_SEC:-2}"
DRAIN_TIMEOUT_SEC="${DRAIN_TIMEOUT_SEC:-30}"
BUILD_RELEASE="${BUILD_RELEASE:-0}"
OUT_DIR="${OUT_DIR:-$ROOT_DIR/var/results}"

# Recommended local profile (Darwin/Linux single-node reproducibility).
V3_SOFT_REJECT_PCT="${V3_SOFT_REJECT_PCT:-85}"
V3_HARD_REJECT_PCT="${V3_HARD_REJECT_PCT:-92}"
V3_KILL_REJECT_PCT="${V3_KILL_REJECT_PCT:-98}"
V3_KILL_AUTO_RECOVER="${V3_KILL_AUTO_RECOVER:-false}"
V3_INGRESS_QUEUE_CAPACITY="${V3_INGRESS_QUEUE_CAPACITY:-131072}"
V3_DURABILITY_QUEUE_CAPACITY="${V3_DURABILITY_QUEUE_CAPACITY:-4000000}"
if [[ -z "${V3_SHARD_COUNT:-}" ]]; then
  if [[ "$(uname -s)" == "Darwin" ]]; then
    V3_SHARD_COUNT=6
  else
    V3_SHARD_COUNT=8
  fi
fi
V3_LOSS_GAP_TIMEOUT_MS="${V3_LOSS_GAP_TIMEOUT_MS:-360000}"
V3_SESSION_LOSS_SUSPECT_THRESHOLD="${V3_SESSION_LOSS_SUSPECT_THRESHOLD:-4096}"
V3_SHARD_LOSS_SUSPECT_THRESHOLD="${V3_SHARD_LOSS_SUSPECT_THRESHOLD:-32768}"
V3_GLOBAL_LOSS_SUSPECT_THRESHOLD="${V3_GLOBAL_LOSS_SUSPECT_THRESHOLD:-131072}"
V3_DURABLE_WORKER_BATCH_MAX="${V3_DURABLE_WORKER_BATCH_MAX:-12}"
V3_DURABLE_WORKER_BATCH_MIN="${V3_DURABLE_WORKER_BATCH_MIN:-12}"
V3_DURABLE_WORKER_BATCH_WAIT_US="${V3_DURABLE_WORKER_BATCH_WAIT_US:-20}"
V3_DURABLE_WORKER_BATCH_WAIT_MIN_US="${V3_DURABLE_WORKER_BATCH_WAIT_MIN_US:-20}"
V3_DURABLE_WORKER_RECEIPT_TIMEOUT_US="${V3_DURABLE_WORKER_RECEIPT_TIMEOUT_US:-5000000}"
V3_DURABLE_WORKER_MAX_INFLIGHT_RECEIPTS="${V3_DURABLE_WORKER_MAX_INFLIGHT_RECEIPTS:-4096}"
V3_DURABLE_WORKER_INFLIGHT_SOFT_CAP_PCT="${V3_DURABLE_WORKER_INFLIGHT_SOFT_CAP_PCT:-50}"
V3_DURABLE_WORKER_INFLIGHT_HARD_CAP_PCT="${V3_DURABLE_WORKER_INFLIGHT_HARD_CAP_PCT:-25}"
V3_DURABLE_CONTROL_PRESET="${V3_DURABLE_CONTROL_PRESET:-hft_stable}"
V3_DURABLE_WORKER_DYNAMIC_INFLIGHT="${V3_DURABLE_WORKER_DYNAMIC_INFLIGHT:-false}"
V3_DURABLE_WORKER_DYNAMIC_INFLIGHT_MIN_CAP_PCT="${V3_DURABLE_WORKER_DYNAMIC_INFLIGHT_MIN_CAP_PCT:-10}"
V3_DURABLE_WORKER_DYNAMIC_INFLIGHT_MAX_CAP_PCT="${V3_DURABLE_WORKER_DYNAMIC_INFLIGHT_MAX_CAP_PCT:-40}"
V3_DURABLE_WORKER_DYNAMIC_INFLIGHT_STRICT_MAX_CAP_PCT="${V3_DURABLE_WORKER_DYNAMIC_INFLIGHT_STRICT_MAX_CAP_PCT:-40}"
V3_DURABLE_PRESSURE_EWMA_ALPHA_PCT="${V3_DURABLE_PRESSURE_EWMA_ALPHA_PCT:-30}"
V3_DURABLE_DYNAMIC_CAP_SLEW_STEP_PCT="${V3_DURABLE_DYNAMIC_CAP_SLEW_STEP_PCT:-8}"
V3_DURABLE_WORKER_BATCH_ADAPTIVE="${V3_DURABLE_WORKER_BATCH_ADAPTIVE:-false}"
V3_DURABLE_WORKER_BATCH_ADAPTIVE_LOW_UTIL_PCT="${V3_DURABLE_WORKER_BATCH_ADAPTIVE_LOW_UTIL_PCT:-15}"
V3_DURABLE_WORKER_BATCH_ADAPTIVE_HIGH_UTIL_PCT="${V3_DURABLE_WORKER_BATCH_ADAPTIVE_HIGH_UTIL_PCT:-70}"
V3_DURABLE_AGE_SOFT_INFLIGHT_CAP_PCT="${V3_DURABLE_AGE_SOFT_INFLIGHT_CAP_PCT:-35}"
V3_DURABLE_AGE_HARD_INFLIGHT_CAP_PCT="${V3_DURABLE_AGE_HARD_INFLIGHT_CAP_PCT:-15}"
V3_DURABLE_SLO_STAGE="${V3_DURABLE_SLO_STAGE:-1}"
V3_DURABLE_SLO_EARLY_SOFT_AGE_US="${V3_DURABLE_SLO_EARLY_SOFT_AGE_US:-100000}"
V3_DURABLE_SLO_EARLY_HARD_AGE_US="${V3_DURABLE_SLO_EARLY_HARD_AGE_US:-220000}"
V3_DURABLE_SOFT_REJECT_PCT="${V3_DURABLE_SOFT_REJECT_PCT:-$V3_SOFT_REJECT_PCT}"
V3_DURABLE_HARD_REJECT_PCT="${V3_DURABLE_HARD_REJECT_PCT:-$V3_HARD_REJECT_PCT}"
V3_DURABLE_BACKLOG_SIGNAL_MIN_QUEUE_PCT="${V3_DURABLE_BACKLOG_SIGNAL_MIN_QUEUE_PCT:-30}"
V3_DURABLE_ADMISSION_SOFT_FSYNC_P99_US="${V3_DURABLE_ADMISSION_SOFT_FSYNC_P99_US:-4000}"
V3_DURABLE_ADMISSION_HARD_FSYNC_P99_US="${V3_DURABLE_ADMISSION_HARD_FSYNC_P99_US:-8000}"
V3_DURABLE_ADMISSION_FSYNC_PRESIGNAL_PCT="${V3_DURABLE_ADMISSION_FSYNC_PRESIGNAL_PCT:-0.75}"
V3_DURABLE_ADMISSION_FSYNC_ONLY_SOFT_SUSTAIN_TICKS="${V3_DURABLE_ADMISSION_FSYNC_ONLY_SOFT_SUSTAIN_TICKS:-0}"
V3_DURABLE_ADMISSION_FSYNC_ONLY_HARD_SUSTAIN_TICKS="${V3_DURABLE_ADMISSION_FSYNC_ONLY_HARD_SUSTAIN_TICKS:-0}"
V3_DURABLE_FSYNC_EWMA_ALPHA_PCT="${V3_DURABLE_FSYNC_EWMA_ALPHA_PCT:-30}"
V3_DURABLE_FSYNC_SOFT_INFLIGHT_CAP_PCT="${V3_DURABLE_FSYNC_SOFT_INFLIGHT_CAP_PCT:-50}"
V3_DURABLE_FSYNC_HARD_INFLIGHT_CAP_PCT="${V3_DURABLE_FSYNC_HARD_INFLIGHT_CAP_PCT:-20}"
V3_DURABLE_FSYNC_SOFT_TRIGGER_US="${V3_DURABLE_FSYNC_SOFT_TRIGGER_US:-4000}"
V3_DURABLE_FSYNC_HARD_TRIGGER_US="${V3_DURABLE_FSYNC_HARD_TRIGGER_US:-8000}"
V3_DURABLE_CONFIRM_SOFT_REJECT_AGE_US="${V3_DURABLE_CONFIRM_SOFT_REJECT_AGE_US:-180000}"
V3_DURABLE_CONFIRM_HARD_REJECT_AGE_US="${V3_DURABLE_CONFIRM_HARD_REJECT_AGE_US:-260000}"
V3_DURABLE_CONFIRM_AGE_FSYNC_LINKED="${V3_DURABLE_CONFIRM_AGE_FSYNC_LINKED:-true}"
V3_DURABLE_CONFIRM_AGE_FSYNC_SOFT_REF_US="${V3_DURABLE_CONFIRM_AGE_FSYNC_SOFT_REF_US:-6000}"
V3_DURABLE_CONFIRM_AGE_FSYNC_HARD_REF_US="${V3_DURABLE_CONFIRM_AGE_FSYNC_HARD_REF_US:-12000}"
V3_DURABLE_CONFIRM_AGE_FSYNC_MAX_RELAX_PCT="${V3_DURABLE_CONFIRM_AGE_FSYNC_MAX_RELAX_PCT:-100}"
V3_DURABLE_CONFIRM_GUARD_SOFT_SLACK_PCT="${V3_DURABLE_CONFIRM_GUARD_SOFT_SLACK_PCT:-20}"
V3_DURABLE_CONFIRM_GUARD_HARD_SLACK_PCT="${V3_DURABLE_CONFIRM_GUARD_HARD_SLACK_PCT:-40}"
V3_DURABLE_CONFIRM_GUARD_SOFT_REQUIRES_ADMISSION="${V3_DURABLE_CONFIRM_GUARD_SOFT_REQUIRES_ADMISSION:-false}"
V3_DURABLE_CONFIRM_GUARD_HARD_REQUIRES_ADMISSION="${V3_DURABLE_CONFIRM_GUARD_HARD_REQUIRES_ADMISSION:-false}"
V3_DURABLE_CONFIRM_GUARD_SECONDARY_REQUIRED="${V3_DURABLE_CONFIRM_GUARD_SECONDARY_REQUIRED:-false}"
V3_DURABLE_CONFIRM_GUARD_MIN_QUEUE_PCT="${V3_DURABLE_CONFIRM_GUARD_MIN_QUEUE_PCT:-0}"
V3_DURABLE_CONFIRM_GUARD_MIN_INFLIGHT_PCT="${V3_DURABLE_CONFIRM_GUARD_MIN_INFLIGHT_PCT:-0}"
V3_DURABLE_CONFIRM_GUARD_MIN_BACKLOG_PER_SEC="${V3_DURABLE_CONFIRM_GUARD_MIN_BACKLOG_PER_SEC:-0}"
V3_DURABLE_CONFIRM_GUARD_SOFT_SUSTAIN_TICKS="${V3_DURABLE_CONFIRM_GUARD_SOFT_SUSTAIN_TICKS:-2}"
V3_DURABLE_CONFIRM_GUARD_HARD_SUSTAIN_TICKS="${V3_DURABLE_CONFIRM_GUARD_HARD_SUSTAIN_TICKS:-2}"
V3_DURABLE_CONFIRM_GUARD_RECOVER_TICKS="${V3_DURABLE_CONFIRM_GUARD_RECOVER_TICKS:-3}"
V3_DURABLE_CONFIRM_GUARD_RECOVER_HYSTERESIS_PCT="${V3_DURABLE_CONFIRM_GUARD_RECOVER_HYSTERESIS_PCT:-85}"
V3_DURABLE_CONFIRM_GUARD_AUTOTUNE="${V3_DURABLE_CONFIRM_GUARD_AUTOTUNE:-true}"
V3_DURABLE_CONFIRM_GUARD_AUTOTUNE_LOW_PRESSURE_PCT="${V3_DURABLE_CONFIRM_GUARD_AUTOTUNE_LOW_PRESSURE_PCT:-35}"
V3_DURABLE_CONFIRM_GUARD_AUTOTUNE_HIGH_PRESSURE_PCT="${V3_DURABLE_CONFIRM_GUARD_AUTOTUNE_HIGH_PRESSURE_PCT:-80}"
FASTPATH_DRAIN_WORKERS="${FASTPATH_DRAIN_WORKERS:-4}"
AUDIT_FDATASYNC_MAX_WAIT_US="${AUDIT_FDATASYNC_MAX_WAIT_US:-80}"
AUDIT_FDATASYNC_MAX_BATCH="${AUDIT_FDATASYNC_MAX_BATCH:-32}"
AUDIT_FDATASYNC_MAX_DEFER_US="${AUDIT_FDATASYNC_MAX_DEFER_US:-0}"
AUDIT_FDATASYNC_MAX_INFLIGHT_AGE_US="${AUDIT_FDATASYNC_MAX_INFLIGHT_AGE_US:-1200}"
AUDIT_FDATASYNC_MAX_PENDING_BYTES="${AUDIT_FDATASYNC_MAX_PENDING_BYTES:-131072}"
AUDIT_FDATASYNC_SERIALIZE="${AUDIT_FDATASYNC_SERIALIZE:-false}"
if [[ -z "${AUDIT_WAL_PREALLOC_BYTES:-}" ]]; then
  if [[ "$(uname -s)" == "Linux" ]]; then
    AUDIT_WAL_PREALLOC_BYTES=67108864
  else
    AUDIT_WAL_PREALLOC_BYTES=0
  fi
fi
AUDIT_WAL_PREALLOC_THRESHOLD_BYTES="${AUDIT_WAL_PREALLOC_THRESHOLD_BYTES:-8388608}"

if ! [[ "$RUNS" =~ ^[0-9]+$ ]] || [[ "$RUNS" -le 0 ]]; then
  echo "FAIL: RUNS must be a positive integer (current: $RUNS)"
  exit 1
fi
if ! [[ "$INTERVAL_SEC" =~ ^[0-9]+$ ]] || [[ "$INTERVAL_SEC" -lt 0 ]]; then
  echo "FAIL: INTERVAL_SEC must be an integer >= 0 (current: $INTERVAL_SEC)"
  exit 1
fi

mkdir -p "$OUT_DIR"
cd "$ROOT_DIR"

STAMP="$(date +%Y%m%d_%H%M%S)"
RAW_TSV="$OUT_DIR/v3_local_strict_gate_${STAMP}.tsv"
LOOP_SUMMARY="$OUT_DIR/v3_local_strict_gate_${STAMP}.summary.txt"
echo -e "run\trc\tcompleted_rps\taccepted_rate\tack_accepted_p99_us\tdurable_confirm_p99_us\tsummary_path" >"$RAW_TSV"

pass_count=0
for run in $(seq 1 "$RUNS"); do
  run_out_dir="$OUT_DIR/v3_local_strict_gate_${STAMP}_run${run}"
  run_audit_log="$run_out_dir/audit.log"
  run_log="$run_out_dir/run.log"
  mkdir -p "$run_out_dir"
  echo "[run ${run}/${RUNS}] OUT_DIR=${run_out_dir}"

  set +e
  HOST="$HOST" \
  PORT="$PORT" \
  DURATION="$DURATION" \
  TARGET_RPS="$TARGET_RPS" \
  TARGET_COMPLETED_RPS="$TARGET_COMPLETED_RPS" \
  TARGET_COMPLETED_RPS_EPSILON="$TARGET_COMPLETED_RPS_EPSILON" \
  TARGET_ACK_P99_US="$TARGET_ACK_P99_US" \
  TARGET_ACK_ACCEPTED_P99_US="$TARGET_ACK_ACCEPTED_P99_US" \
  TARGET_ACCEPTED_RATE="$TARGET_ACCEPTED_RATE" \
  TARGET_DURABLE_CONFIRM_P99_US="$TARGET_DURABLE_CONFIRM_P99_US" \
  WARN_DURABLE_CONFIRM_P99_US="$WARN_DURABLE_CONFIRM_P99_US" \
  TARGET_REJECTED_KILLED_MAX="$TARGET_REJECTED_KILLED_MAX" \
  TARGET_LOSS_SUSPECT_MAX="$TARGET_LOSS_SUSPECT_MAX" \
  TARGET_OFFERED_RPS_RATIO_MIN="$TARGET_OFFERED_RPS_RATIO_MIN" \
  TARGET_DROPPED_OFFER_RATIO_MAX="$TARGET_DROPPED_OFFER_RATIO_MAX" \
  TARGET_UNSENT_TOTAL_MAX="$TARGET_UNSENT_TOTAL_MAX" \
  TARGET_STRICT_LANE_TOPOLOGY="$TARGET_STRICT_LANE_TOPOLOGY" \
  TARGET_STRICT_PER_LANE_CHECKS="$TARGET_STRICT_PER_LANE_CHECKS" \
  TARGET_DURABLE_INFLIGHT_SKEW_RATIO_MAX="$TARGET_DURABLE_INFLIGHT_SKEW_RATIO_MAX" \
  TARGET_DURABLE_INFLIGHT_HOT_LANE_SHARE_MAX="$TARGET_DURABLE_INFLIGHT_HOT_LANE_SHARE_MAX" \
  WARN_DURABLE_INFLIGHT_SKEW_RATIO="$WARN_DURABLE_INFLIGHT_SKEW_RATIO" \
  WARN_DURABLE_INFLIGHT_HOT_LANE_SHARE="$WARN_DURABLE_INFLIGHT_HOT_LANE_SHARE" \
  V3_INGRESS_TRANSPORT="$V3_INGRESS_TRANSPORT" \
  V3_TCP_PORT="$V3_TCP_PORT" \
  LOAD_WORKERS="$LOAD_WORKERS" \
  LOAD_ACCOUNTS="$LOAD_ACCOUNTS" \
  LOAD_QUEUE_CAPACITY="$LOAD_QUEUE_CAPACITY" \
  LOAD_FINAL_CATCHUP="$LOAD_FINAL_CATCHUP" \
  REQUEST_TIMEOUT_SEC="$REQUEST_TIMEOUT_SEC" \
  DRAIN_TIMEOUT_SEC="$DRAIN_TIMEOUT_SEC" \
  BUILD_RELEASE="$BUILD_RELEASE" \
  OUT_DIR="$run_out_dir" \
  V3_SOFT_REJECT_PCT="$V3_SOFT_REJECT_PCT" \
  V3_HARD_REJECT_PCT="$V3_HARD_REJECT_PCT" \
  V3_KILL_REJECT_PCT="$V3_KILL_REJECT_PCT" \
  V3_KILL_AUTO_RECOVER="$V3_KILL_AUTO_RECOVER" \
  V3_INGRESS_QUEUE_CAPACITY="$V3_INGRESS_QUEUE_CAPACITY" \
  V3_DURABILITY_QUEUE_CAPACITY="$V3_DURABILITY_QUEUE_CAPACITY" \
  V3_SHARD_COUNT="$V3_SHARD_COUNT" \
  V3_LOSS_GAP_TIMEOUT_MS="$V3_LOSS_GAP_TIMEOUT_MS" \
  V3_SESSION_LOSS_SUSPECT_THRESHOLD="$V3_SESSION_LOSS_SUSPECT_THRESHOLD" \
  V3_SHARD_LOSS_SUSPECT_THRESHOLD="$V3_SHARD_LOSS_SUSPECT_THRESHOLD" \
  V3_GLOBAL_LOSS_SUSPECT_THRESHOLD="$V3_GLOBAL_LOSS_SUSPECT_THRESHOLD" \
  V3_DURABLE_WORKER_BATCH_MAX="$V3_DURABLE_WORKER_BATCH_MAX" \
  V3_DURABLE_WORKER_BATCH_MIN="$V3_DURABLE_WORKER_BATCH_MIN" \
  V3_DURABLE_WORKER_BATCH_WAIT_US="$V3_DURABLE_WORKER_BATCH_WAIT_US" \
  V3_DURABLE_WORKER_BATCH_WAIT_MIN_US="$V3_DURABLE_WORKER_BATCH_WAIT_MIN_US" \
  V3_DURABLE_WORKER_RECEIPT_TIMEOUT_US="$V3_DURABLE_WORKER_RECEIPT_TIMEOUT_US" \
  V3_DURABLE_WORKER_MAX_INFLIGHT_RECEIPTS="$V3_DURABLE_WORKER_MAX_INFLIGHT_RECEIPTS" \
  V3_DURABLE_WORKER_INFLIGHT_SOFT_CAP_PCT="$V3_DURABLE_WORKER_INFLIGHT_SOFT_CAP_PCT" \
  V3_DURABLE_WORKER_INFLIGHT_HARD_CAP_PCT="$V3_DURABLE_WORKER_INFLIGHT_HARD_CAP_PCT" \
  V3_DURABLE_CONTROL_PRESET="$V3_DURABLE_CONTROL_PRESET" \
  V3_DURABLE_WORKER_DYNAMIC_INFLIGHT="$V3_DURABLE_WORKER_DYNAMIC_INFLIGHT" \
  V3_DURABLE_WORKER_DYNAMIC_INFLIGHT_MIN_CAP_PCT="$V3_DURABLE_WORKER_DYNAMIC_INFLIGHT_MIN_CAP_PCT" \
  V3_DURABLE_WORKER_DYNAMIC_INFLIGHT_MAX_CAP_PCT="$V3_DURABLE_WORKER_DYNAMIC_INFLIGHT_MAX_CAP_PCT" \
  V3_DURABLE_WORKER_DYNAMIC_INFLIGHT_STRICT_MAX_CAP_PCT="$V3_DURABLE_WORKER_DYNAMIC_INFLIGHT_STRICT_MAX_CAP_PCT" \
  V3_DURABLE_PRESSURE_EWMA_ALPHA_PCT="$V3_DURABLE_PRESSURE_EWMA_ALPHA_PCT" \
  V3_DURABLE_DYNAMIC_CAP_SLEW_STEP_PCT="$V3_DURABLE_DYNAMIC_CAP_SLEW_STEP_PCT" \
  V3_DURABLE_WORKER_BATCH_ADAPTIVE="$V3_DURABLE_WORKER_BATCH_ADAPTIVE" \
  V3_DURABLE_WORKER_BATCH_ADAPTIVE_LOW_UTIL_PCT="$V3_DURABLE_WORKER_BATCH_ADAPTIVE_LOW_UTIL_PCT" \
  V3_DURABLE_WORKER_BATCH_ADAPTIVE_HIGH_UTIL_PCT="$V3_DURABLE_WORKER_BATCH_ADAPTIVE_HIGH_UTIL_PCT" \
  V3_DURABLE_AGE_SOFT_INFLIGHT_CAP_PCT="$V3_DURABLE_AGE_SOFT_INFLIGHT_CAP_PCT" \
  V3_DURABLE_AGE_HARD_INFLIGHT_CAP_PCT="$V3_DURABLE_AGE_HARD_INFLIGHT_CAP_PCT" \
  V3_DURABLE_SLO_STAGE="$V3_DURABLE_SLO_STAGE" \
  V3_DURABLE_SLO_EARLY_SOFT_AGE_US="$V3_DURABLE_SLO_EARLY_SOFT_AGE_US" \
  V3_DURABLE_SLO_EARLY_HARD_AGE_US="$V3_DURABLE_SLO_EARLY_HARD_AGE_US" \
  V3_DURABLE_ADMISSION_SOFT_FSYNC_P99_US="$V3_DURABLE_ADMISSION_SOFT_FSYNC_P99_US" \
  V3_DURABLE_ADMISSION_HARD_FSYNC_P99_US="$V3_DURABLE_ADMISSION_HARD_FSYNC_P99_US" \
  V3_DURABLE_SOFT_REJECT_PCT="$V3_DURABLE_SOFT_REJECT_PCT" \
  V3_DURABLE_HARD_REJECT_PCT="$V3_DURABLE_HARD_REJECT_PCT" \
  V3_DURABLE_BACKLOG_SIGNAL_MIN_QUEUE_PCT="$V3_DURABLE_BACKLOG_SIGNAL_MIN_QUEUE_PCT" \
  V3_DURABLE_ADMISSION_FSYNC_PRESIGNAL_PCT="$V3_DURABLE_ADMISSION_FSYNC_PRESIGNAL_PCT" \
  V3_DURABLE_ADMISSION_FSYNC_ONLY_SOFT_SUSTAIN_TICKS="$V3_DURABLE_ADMISSION_FSYNC_ONLY_SOFT_SUSTAIN_TICKS" \
  V3_DURABLE_ADMISSION_FSYNC_ONLY_HARD_SUSTAIN_TICKS="$V3_DURABLE_ADMISSION_FSYNC_ONLY_HARD_SUSTAIN_TICKS" \
  V3_DURABLE_FSYNC_EWMA_ALPHA_PCT="$V3_DURABLE_FSYNC_EWMA_ALPHA_PCT" \
  V3_DURABLE_FSYNC_SOFT_INFLIGHT_CAP_PCT="$V3_DURABLE_FSYNC_SOFT_INFLIGHT_CAP_PCT" \
  V3_DURABLE_FSYNC_HARD_INFLIGHT_CAP_PCT="$V3_DURABLE_FSYNC_HARD_INFLIGHT_CAP_PCT" \
  V3_DURABLE_FSYNC_SOFT_TRIGGER_US="$V3_DURABLE_FSYNC_SOFT_TRIGGER_US" \
  V3_DURABLE_FSYNC_HARD_TRIGGER_US="$V3_DURABLE_FSYNC_HARD_TRIGGER_US" \
  V3_DURABLE_CONFIRM_SOFT_REJECT_AGE_US="$V3_DURABLE_CONFIRM_SOFT_REJECT_AGE_US" \
  V3_DURABLE_CONFIRM_HARD_REJECT_AGE_US="$V3_DURABLE_CONFIRM_HARD_REJECT_AGE_US" \
  V3_DURABLE_CONFIRM_AGE_FSYNC_LINKED="$V3_DURABLE_CONFIRM_AGE_FSYNC_LINKED" \
  V3_DURABLE_CONFIRM_AGE_FSYNC_SOFT_REF_US="$V3_DURABLE_CONFIRM_AGE_FSYNC_SOFT_REF_US" \
  V3_DURABLE_CONFIRM_AGE_FSYNC_HARD_REF_US="$V3_DURABLE_CONFIRM_AGE_FSYNC_HARD_REF_US" \
  V3_DURABLE_CONFIRM_AGE_FSYNC_MAX_RELAX_PCT="$V3_DURABLE_CONFIRM_AGE_FSYNC_MAX_RELAX_PCT" \
  V3_DURABLE_CONFIRM_GUARD_SOFT_SLACK_PCT="$V3_DURABLE_CONFIRM_GUARD_SOFT_SLACK_PCT" \
  V3_DURABLE_CONFIRM_GUARD_HARD_SLACK_PCT="$V3_DURABLE_CONFIRM_GUARD_HARD_SLACK_PCT" \
  V3_DURABLE_CONFIRM_GUARD_SOFT_REQUIRES_ADMISSION="$V3_DURABLE_CONFIRM_GUARD_SOFT_REQUIRES_ADMISSION" \
  V3_DURABLE_CONFIRM_GUARD_HARD_REQUIRES_ADMISSION="$V3_DURABLE_CONFIRM_GUARD_HARD_REQUIRES_ADMISSION" \
  V3_DURABLE_CONFIRM_GUARD_SECONDARY_REQUIRED="$V3_DURABLE_CONFIRM_GUARD_SECONDARY_REQUIRED" \
  V3_DURABLE_CONFIRM_GUARD_MIN_QUEUE_PCT="$V3_DURABLE_CONFIRM_GUARD_MIN_QUEUE_PCT" \
  V3_DURABLE_CONFIRM_GUARD_MIN_INFLIGHT_PCT="$V3_DURABLE_CONFIRM_GUARD_MIN_INFLIGHT_PCT" \
  V3_DURABLE_CONFIRM_GUARD_MIN_BACKLOG_PER_SEC="$V3_DURABLE_CONFIRM_GUARD_MIN_BACKLOG_PER_SEC" \
  V3_DURABLE_CONFIRM_GUARD_SOFT_SUSTAIN_TICKS="$V3_DURABLE_CONFIRM_GUARD_SOFT_SUSTAIN_TICKS" \
  V3_DURABLE_CONFIRM_GUARD_HARD_SUSTAIN_TICKS="$V3_DURABLE_CONFIRM_GUARD_HARD_SUSTAIN_TICKS" \
  V3_DURABLE_CONFIRM_GUARD_RECOVER_TICKS="$V3_DURABLE_CONFIRM_GUARD_RECOVER_TICKS" \
  V3_DURABLE_CONFIRM_GUARD_RECOVER_HYSTERESIS_PCT="$V3_DURABLE_CONFIRM_GUARD_RECOVER_HYSTERESIS_PCT" \
  V3_DURABLE_CONFIRM_GUARD_AUTOTUNE="$V3_DURABLE_CONFIRM_GUARD_AUTOTUNE" \
  V3_DURABLE_CONFIRM_GUARD_AUTOTUNE_LOW_PRESSURE_PCT="$V3_DURABLE_CONFIRM_GUARD_AUTOTUNE_LOW_PRESSURE_PCT" \
  V3_DURABLE_CONFIRM_GUARD_AUTOTUNE_HIGH_PRESSURE_PCT="$V3_DURABLE_CONFIRM_GUARD_AUTOTUNE_HIGH_PRESSURE_PCT" \
  FASTPATH_DRAIN_WORKERS="$FASTPATH_DRAIN_WORKERS" \
  AUDIT_FDATASYNC_MAX_WAIT_US="$AUDIT_FDATASYNC_MAX_WAIT_US" \
  AUDIT_FDATASYNC_MAX_BATCH="$AUDIT_FDATASYNC_MAX_BATCH" \
  AUDIT_FDATASYNC_MAX_DEFER_US="$AUDIT_FDATASYNC_MAX_DEFER_US" \
  AUDIT_FDATASYNC_MAX_INFLIGHT_AGE_US="$AUDIT_FDATASYNC_MAX_INFLIGHT_AGE_US" \
  AUDIT_FDATASYNC_MAX_PENDING_BYTES="$AUDIT_FDATASYNC_MAX_PENDING_BYTES" \
  AUDIT_FDATASYNC_SERIALIZE="$AUDIT_FDATASYNC_SERIALIZE" \
  AUDIT_WAL_PREALLOC_BYTES="$AUDIT_WAL_PREALLOC_BYTES" \
  AUDIT_WAL_PREALLOC_THRESHOLD_BYTES="$AUDIT_WAL_PREALLOC_THRESHOLD_BYTES" \
  AUDIT_LOG_PATH="$run_audit_log" \
  ENFORCE_GATE=1 \
  scripts/ops/run_v3_open_loop_probe.sh >"$run_log" 2>&1
  rc=$?
  set -e

  summary_path="$(ls -1t "$run_out_dir"/v3_open_loop_*.summary.txt 2>/dev/null | head -n1 || true)"
  completed_rps="NA"
  accepted_rate="NA"
  ack_accepted_p99="NA"
  durable_confirm_p99="NA"
  if [[ -n "$summary_path" ]]; then
    completed_rps="$(awk -F= '/^completed_rps=/{print $2}' "$summary_path" | tail -n1)"
    accepted_rate="$(awk -F= '/^server_accepted_rate=/{print $2}' "$summary_path" | tail -n1)"
    ack_accepted_p99="$(awk -F= '/^server_live_ack_accepted_p99_us=/{print $2}' "$summary_path" | tail -n1)"
    durable_confirm_p99="$(awk -F= '/^server_durable_confirm_p99_us=/{print $2}' "$summary_path" | tail -n1)"
    completed_rps="${completed_rps:-NA}"
    accepted_rate="${accepted_rate:-NA}"
    ack_accepted_p99="${ack_accepted_p99:-NA}"
    durable_confirm_p99="${durable_confirm_p99:-NA}"
  fi
  echo -e "${run}\t${rc}\t${completed_rps}\t${accepted_rate}\t${ack_accepted_p99}\t${durable_confirm_p99}\t${summary_path}" >>"$RAW_TSV"
  echo "[run ${run}/${RUNS}] rc=${rc} completed_rps=${completed_rps} accepted_rate=${accepted_rate} ack_accepted_p99_us=${ack_accepted_p99} durable_confirm_p99_us=${durable_confirm_p99}"
  if [[ "$rc" -eq 0 ]]; then
    pass_count=$((pass_count + 1))
  fi
  if [[ "$run" -lt "$RUNS" && "$INTERVAL_SEC" -gt 0 ]]; then
    sleep "$INTERVAL_SEC"
  fi
done

pass_ratio="$(awk -v p="$pass_count" -v r="$RUNS" 'BEGIN{if(r<=0){print 0}else{printf "%.6f", p/r}}')"

{
  echo "v3_local_strict_gate_loop"
  echo "runs=${RUNS}"
  echo "pass_count=${pass_count}"
  echo "pass_ratio=${pass_ratio}"
  echo "required_pass_ratio=${MIN_PASS_RATIO}"
  echo "target_completed_rps=${TARGET_COMPLETED_RPS}"
  echo "target_completed_rps_epsilon=${TARGET_COMPLETED_RPS_EPSILON}"
  echo "target_live_ack_p99_us=${TARGET_ACK_P99_US}"
  echo "target_live_ack_accepted_p99_us=${TARGET_ACK_ACCEPTED_P99_US}"
  echo "target_accepted_rate=${TARGET_ACCEPTED_RATE}"
  echo "target_durable_confirm_p99_us=${TARGET_DURABLE_CONFIRM_P99_US}"
  echo "raw_tsv=${RAW_TSV}"
} >"$LOOP_SUMMARY"

echo "[artifacts] raw=${RAW_TSV}"
echo "[artifacts] summary=${LOOP_SUMMARY}"

ok="$(awk -v v="$pass_ratio" -v t="$MIN_PASS_RATIO" 'BEGIN{print (v+0>=t+0)?1:0}')"
if [[ "$ok" == "1" ]]; then
  echo "PASS: local strict gate satisfied (pass_ratio=${pass_ratio}, required=${MIN_PASS_RATIO})"
  exit 0
fi

echo "FAIL: local strict gate failed (pass_ratio=${pass_ratio}, required=${MIN_PASS_RATIO})"
exit 1
