#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/../../gateway-rust"

BACKPRESSURE_INFLIGHT_DYNAMIC="${BACKPRESSURE_INFLIGHT_DYNAMIC:-1}" \
BACKPRESSURE_INFLIGHT_TARGET_WAL_AGE_SEC="${BACKPRESSURE_INFLIGHT_TARGET_WAL_AGE_SEC:-1.0}" \
BACKPRESSURE_INFLIGHT_ALPHA="${BACKPRESSURE_INFLIGHT_ALPHA:-0.8}" \
BACKPRESSURE_INFLIGHT_BETA="${BACKPRESSURE_INFLIGHT_BETA:-0.2}" \
BACKPRESSURE_INFLIGHT_MIN="${BACKPRESSURE_INFLIGHT_MIN:-256}" \
BACKPRESSURE_INFLIGHT_CAP="${BACKPRESSURE_INFLIGHT_CAP:-10000}" \
BACKPRESSURE_INFLIGHT_TICK_MS="${BACKPRESSURE_INFLIGHT_TICK_MS:-250}" \
BACKPRESSURE_INFLIGHT_SLEW_RATIO="${BACKPRESSURE_INFLIGHT_SLEW_RATIO:-0.2}" \
BACKPRESSURE_INFLIGHT_HYSTERESIS_OFF_RATIO="${BACKPRESSURE_INFLIGHT_HYSTERESIS_OFF_RATIO:-0.9}" \
BACKPRESSURE_INFLIGHT_INITIAL="${BACKPRESSURE_INFLIGHT_INITIAL:-2000}" \
GATEWAY_PORT="${GATEWAY_PORT:-8082}" \
GATEWAY_TCP_PORT="${GATEWAY_TCP_PORT:-0}" \
AUDIT_ASYNC_WAL="${AUDIT_ASYNC_WAL:-1}" \
AUDIT_FDATASYNC="${AUDIT_FDATASYNC:-1}" \
JWT_HS256_SECRET="${JWT_HS256_SECRET:-secret123}" \
cargo run --bin gateway-rust
