#!/usr/bin/env python3
from __future__ import annotations

import argparse
import datetime as dt
import json
import os
import platform
import re
import shlex
import shutil
import signal
import subprocess
import tempfile
import time
from pathlib import Path
from typing import Any

# Local imports from scripts/ops.
from ai_incident_agent import run_agent_with_llm, run_deterministic

DEFAULT_PERF_EVENTS = (
    "cycles,"
    "instructions,"
    "cache-references,"
    "cache-misses,"
    "branches,"
    "branch-misses,"
    "context-switches,"
    "cpu-migrations,"
    "task-clock"
)


def now_iso() -> str:
    return dt.datetime.now(dt.timezone.utc).replace(microsecond=0).isoformat()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run probe + collect platform counters + feed AI triage"
    )
    parser.add_argument("--results-dir", default="var/results")
    parser.add_argument(
        "--counter-mode",
        default="auto",
        choices=("auto", "linux-perf", "mac-powermetrics", "none"),
    )
    parser.add_argument("--perf-events", default=DEFAULT_PERF_EVENTS)
    parser.add_argument("--powermetrics-sample-ms", type=int, default=1000)
    parser.add_argument("--provider", default="mock", choices=("mock", "openai"))
    parser.add_argument(
        "--model",
        default=None,
        help="Default: mock-triage-v1 (mock) / gpt-5-nano (openai)",
    )
    parser.add_argument("--db-path", default="var/ai_index/docs.sqlite")
    parser.add_argument("--top-k", type=int, default=5)
    parser.add_argument("--recent-window", type=int, default=5)
    parser.add_argument("--skip-ai", action="store_true")
    parser.add_argument("--baseline-run-name", default=None)
    parser.add_argument("--out", default=None, help="Optional combined output JSON path")
    parser.add_argument(
        "--env",
        action="append",
        default=[],
        help="Extra environment variable KEY=VALUE (repeatable)",
    )
    parser.add_argument(
        "command",
        nargs=argparse.REMAINDER,
        help="Command to execute (pass after --)",
    )
    return parser.parse_args()


def parse_env_overrides(items: list[str]) -> dict[str, str]:
    out: dict[str, str] = {}
    for item in items:
        if "=" not in item:
            raise ValueError(f"--env must be KEY=VALUE: {item}")
        key, value = item.split("=", 1)
        key = key.strip()
        if not key:
            raise ValueError(f"invalid empty env key: {item}")
        out[key] = value
    return out


def parse_key_value_file(path: Path) -> dict[str, str]:
    data: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        if "=" not in line:
            continue
        key, value = line.split("=", 1)
        data[key.strip()] = value.strip()
    return data


def list_summary_files(results_dir: Path) -> list[Path]:
    files = list(results_dir.glob("*.summary.txt")) + list(results_dir.glob("*/*.summary.txt"))
    return [p for p in files if p.exists()]


def detect_run_summary(
    results_dir: Path,
    start_ts: float,
    before_set: set[str],
) -> Path:
    candidates = []
    for path in list_summary_files(results_dir):
        key = str(path.resolve())
        mtime = path.stat().st_mtime
        if key not in before_set or mtime >= start_ts - 1.0:
            candidates.append(path)
    if not candidates:
        raise FileNotFoundError("no summary.txt generated by the command")
    candidates.sort(key=lambda p: p.stat().st_mtime, reverse=True)
    return candidates[0]


def normalize_run_name(summary_path: Path) -> str:
    name = summary_path.name
    if name.endswith(".summary.txt"):
        return name[: -len(".summary.txt")]
    return summary_path.stem


def resolve_counter_mode(requested: str) -> str:
    if requested != "auto":
        return requested
    system = platform.system().lower()
    if system == "linux" and shutil.which("perf"):
        return "linux-perf"
    if system == "darwin" and shutil.which("powermetrics"):
        return "mac-powermetrics"
    return "none"


def canonical_event_name(event: str) -> str:
    base = event.strip()
    if ":" in base:
        base = base.split(":", 1)[0]
    return base


def parse_perf_stat_csv(path: Path) -> dict[str, float]:
    counters: dict[str, float] = {}
    if not path.exists():
        return counters
    for raw in path.read_text(encoding="utf-8", errors="replace").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split(",")
        if len(parts) < 3:
            continue
        value_text = parts[0].strip().replace(" ", "")
        unit = parts[1].strip()
        event = canonical_event_name(parts[2].strip())
        if not value_text or value_text in ("<notcounted>", "<notsupported>", "nan"):
            continue
        try:
            value = float(value_text)
        except ValueError:
            continue
        if unit == "msec" and event == "task-clock":
            value /= 1000.0
        if event in counters:
            counters[event] += value
        else:
            counters[event] = value
    return counters


def parse_powermetrics_text(path: Path) -> dict[str, float]:
    if not path.exists():
        return {}
    text = path.read_text(encoding="utf-8", errors="replace")
    patterns = {
        "cpu_avg_freq_pct": re.compile(
            r"CPU Average frequency as fraction of nominal:\s*([0-9]+(?:\.[0-9]+)?)%"
        ),
        "cpu_power_mw": re.compile(r"CPU Power:\s*([0-9]+(?:\.[0-9]+)?)\s*mW"),
        "package_power_mw": re.compile(r"Combined Power.*?:\s*([0-9]+(?:\.[0-9]+)?)\s*mW"),
    }
    out: dict[str, float] = {}
    for key, pat in patterns.items():
        matches = [float(m) for m in pat.findall(text)]
        if not matches:
            continue
        out[key] = sum(matches) / len(matches)
    return out


def compute_derived_metrics(
    counters: dict[str, float],
    summary: dict[str, str],
) -> dict[str, float]:
    def get_counter(key: str) -> float | None:
        if key in counters:
            return counters[key]
        alt = key.replace("-", "_") if "-" in key else key.replace("_", "-")
        return counters.get(alt)

    derived: dict[str, float] = {}
    cycles = get_counter("cycles")
    instructions = get_counter("instructions")
    cache_refs = get_counter("cache-references")
    cache_misses = get_counter("cache-misses")
    branches = get_counter("branches")
    branch_misses = get_counter("branch-misses")
    if cycles and cycles > 0 and instructions is not None:
        derived["ipc"] = instructions / cycles
    if cache_refs and cache_refs > 0 and cache_misses is not None:
        derived["cache_miss_rate"] = cache_misses / cache_refs
    if branches and branches > 0 and branch_misses is not None:
        derived["branch_miss_rate"] = branch_misses / branches

    completed_rps = float(summary.get("completed_rps", "0") or "0")
    duration_sec = float(summary.get("duration_sec", "0") or "0")
    completed_total = completed_rps * duration_sec
    if completed_total > 0:
        if cycles is not None:
            derived["cycles_per_completed"] = cycles / completed_total
        if instructions is not None:
            derived["instructions_per_completed"] = instructions / completed_total
        if cache_misses is not None:
            derived["cache_misses_per_completed"] = cache_misses / completed_total
        if branch_misses is not None:
            derived["branch_misses_per_completed"] = branch_misses / completed_total
    return derived


def compute_delta_vs_baseline(
    baseline: dict[str, Any] | None,
    counters: dict[str, float],
    derived: dict[str, float],
) -> dict[str, float]:
    if not baseline:
        return {}
    out: dict[str, float] = {}
    base_counters = baseline.get("counters", {})
    if isinstance(base_counters, dict):
        for key, value in counters.items():
            base = base_counters.get(key)
            if not isinstance(base, (int, float)) or base == 0:
                continue
            out[f"counters.{key}"] = ((value - base) / abs(base)) * 100.0
    base_derived = baseline.get("derived", {})
    if isinstance(base_derived, dict):
        for key, value in derived.items():
            base = base_derived.get(key)
            if not isinstance(base, (int, float)) or base == 0:
                continue
            out[key] = ((value - base) / abs(base)) * 100.0
    return out


def run_command_with_linux_perf(
    command: list[str],
    env: dict[str, str],
    events: str,
    perf_raw_path: Path,
) -> int:
    wrapped = [
        "perf",
        "stat",
        "-x,",
        "-o",
        str(perf_raw_path),
        "-e",
        events,
        "--",
        *command,
    ]
    return subprocess.run(wrapped, env=env, check=False).returncode


def run_command_with_mac_powermetrics(
    command: list[str],
    env: dict[str, str],
    sample_ms: int,
    powermetrics_raw_path: Path,
    powermetrics_err_path: Path,
) -> tuple[int, str]:
    note = ""
    sampler_cmd_candidates = [
        [
            "sudo",
            "-n",
            "powermetrics",
            "--sample-rate",
            str(sample_ms),
            "--sample-count",
            "-1",
            "--samplers",
            "cpu_power,tasks",
            "--output-file",
            str(powermetrics_raw_path),
        ],
        [
            "powermetrics",
            "--sample-rate",
            str(sample_ms),
            "--sample-count",
            "-1",
            "--samplers",
            "cpu_power,tasks",
            "--output-file",
            str(powermetrics_raw_path),
        ],
    ]

    sampler_proc: subprocess.Popen[str] | None = None
    err_file = powermetrics_err_path.open("w", encoding="utf-8")
    try:
        for candidate in sampler_cmd_candidates:
            try:
                sampler_proc = subprocess.Popen(
                    candidate,
                    stdout=subprocess.DEVNULL,
                    stderr=err_file,
                    env=env,
                    text=True,
                )
                time.sleep(0.2)
                if sampler_proc.poll() is None:
                    note = f"powermetrics_started:{' '.join(candidate[:2])}"
                    break
                note = "powermetrics_start_failed"
            except FileNotFoundError:
                note = "powermetrics_not_found"
                continue
            except PermissionError:
                note = "powermetrics_permission_denied"
                continue
        rc = subprocess.run(command, env=env, check=False).returncode
    finally:
        if sampler_proc and sampler_proc.poll() is None:
            sampler_proc.send_signal(signal.SIGINT)
            try:
                sampler_proc.wait(timeout=5)
            except subprocess.TimeoutExpired:
                sampler_proc.kill()
                sampler_proc.wait(timeout=2)
        err_file.close()
    return rc, note


def run_plain_command(command: list[str], env: dict[str, str]) -> int:
    return subprocess.run(command, env=env, check=False).returncode


def build_command(raw_command: list[str]) -> list[str]:
    cmd = list(raw_command)
    if cmd and cmd[0] == "--":
        cmd = cmd[1:]
    if not cmd:
        raise ValueError("missing command. pass target command after --")
    return cmd


def default_model(provider: str) -> str:
    if provider == "openai":
        return "gpt-5-nano"
    return "mock-triage-v1"


def main() -> int:
    args = parse_args()
    results_dir = Path(args.results_dir)
    results_dir.mkdir(parents=True, exist_ok=True)
    command = build_command(args.command)
    env = dict(os.environ)
    env.update(parse_env_overrides(args.env))

    before = {str(p.resolve()) for p in list_summary_files(results_dir)}
    start_ts = time.time()
    mode_used = resolve_counter_mode(args.counter_mode)

    perf_raw_path: Path | None = None
    powermetrics_raw_path: Path | None = None
    powermetrics_err_path: Path | None = None
    collection_note = ""

    with tempfile.TemporaryDirectory(prefix="ai_perf_probe_") as tmpdir:
        tmp = Path(tmpdir)
        if mode_used == "linux-perf":
            perf_raw_path = tmp / "perf_stat.csv"
            rc = run_command_with_linux_perf(
                command=command,
                env=env,
                events=args.perf_events,
                perf_raw_path=perf_raw_path,
            )
        elif mode_used == "mac-powermetrics":
            powermetrics_raw_path = tmp / "powermetrics.txt"
            powermetrics_err_path = tmp / "powermetrics.err.txt"
            rc, collection_note = run_command_with_mac_powermetrics(
                command=command,
                env=env,
                sample_ms=args.powermetrics_sample_ms,
                powermetrics_raw_path=powermetrics_raw_path,
                powermetrics_err_path=powermetrics_err_path,
            )
        else:
            rc = run_plain_command(command=command, env=env)

        end_ts = time.time()
        summary_path = detect_run_summary(results_dir, start_ts, before)
        run_name = normalize_run_name(summary_path)
        metrics_path = results_dir / f"{run_name}.metrics.prom"
        summary = parse_key_value_file(summary_path)

        counters: dict[str, float] = {}
        if mode_used == "linux-perf" and perf_raw_path:
            counters = parse_perf_stat_csv(perf_raw_path)
        elif mode_used == "mac-powermetrics" and powermetrics_raw_path:
            counters = parse_powermetrics_text(powermetrics_raw_path)

        perf_stat_copy_path: Path | None = None
        powermetrics_copy_path: Path | None = None
        powermetrics_err_copy_path: Path | None = None
        if perf_raw_path and perf_raw_path.exists():
            perf_stat_copy_path = results_dir / f"{run_name}.perf_stat.csv"
            perf_stat_copy_path.write_text(
                perf_raw_path.read_text(encoding="utf-8", errors="replace"),
                encoding="utf-8",
            )
        if powermetrics_raw_path and powermetrics_raw_path.exists():
            powermetrics_copy_path = results_dir / f"{run_name}.powermetrics.txt"
            powermetrics_copy_path.write_text(
                powermetrics_raw_path.read_text(encoding="utf-8", errors="replace"),
                encoding="utf-8",
            )
        if powermetrics_err_path and powermetrics_err_path.exists():
            powermetrics_err_copy_path = results_dir / f"{run_name}.powermetrics.err.txt"
            powermetrics_err_copy_path.write_text(
                powermetrics_err_path.read_text(encoding="utf-8", errors="replace"),
                encoding="utf-8",
            )

        derived = compute_derived_metrics(counters, summary)

        baseline: dict[str, Any] | None = None
        if args.baseline_run_name:
            baseline_path = results_dir / f"{args.baseline_run_name}.perf.json"
            if baseline_path.exists():
                try:
                    baseline = json.loads(
                        baseline_path.read_text(encoding="utf-8", errors="replace")
                    )
                except json.JSONDecodeError:
                    baseline = None
        delta = compute_delta_vs_baseline(baseline, counters, derived)

        perf_profile = {
            "run_name": run_name,
            "generated_at": now_iso(),
            "platform": platform.platform(),
            "counter_mode_requested": args.counter_mode,
            "counter_mode_used": mode_used,
            "collection_ok": bool(counters),
            "collection_note": collection_note,
            "command": shlex.join(command),
            "exit_code": rc,
            "summary_path": str(summary_path),
            "metrics_path": str(metrics_path) if metrics_path.exists() else None,
            "window_start_epoch": start_ts,
            "window_end_epoch": end_ts,
            "window_duration_sec": end_ts - start_ts,
            "counters": counters,
            "derived": derived,
            "baseline_run_name": args.baseline_run_name,
            "delta_vs_baseline": delta,
            "raw_paths": {
                "perf_stat_csv": str(perf_stat_copy_path) if perf_stat_copy_path else None,
                "powermetrics_txt": str(powermetrics_copy_path) if powermetrics_copy_path else None,
                "powermetrics_err": (
                    str(powermetrics_err_copy_path) if powermetrics_err_copy_path else None
                ),
            },
        }
        perf_profile_path = results_dir / f"{run_name}.perf.json"
        perf_profile_path.write_text(
            json.dumps(perf_profile, ensure_ascii=False, indent=2) + "\n",
            encoding="utf-8",
        )

        triage_report: dict[str, Any] | None = None
        triage_path: Path | None = None
        if not args.skip_ai:
            provider = args.provider
            model = args.model or default_model(provider)
            try:
                triage_report = run_agent_with_llm(
                    run_name=run_name,
                    results_dir=results_dir,
                    db_path=Path(args.db_path),
                    provider=provider,
                    model=model,
                    top_k=args.top_k,
                    recent_window=args.recent_window,
                )
            except Exception:
                triage_report = run_deterministic(run_name, results_dir)
            triage_path = results_dir / f"{run_name}.triage.json"
            triage_path.write_text(
                json.dumps(triage_report, ensure_ascii=False, indent=2) + "\n",
                encoding="utf-8",
            )

        combined = {
            "run_name": run_name,
            "exit_code": rc,
            "summary_path": str(summary_path),
            "perf_profile_path": str(perf_profile_path),
            "triage_path": str(triage_path) if triage_path else None,
            "counter_mode_used": mode_used,
            "collection_ok": bool(counters),
            "collection_note": collection_note,
            "counters": counters,
            "derived": derived,
            "delta_vs_baseline": delta,
        }
        payload = json.dumps(combined, ensure_ascii=False, indent=2)
        if args.out:
            out_path = Path(args.out)
            out_path.parent.mkdir(parents=True, exist_ok=True)
            out_path.write_text(payload + "\n", encoding="utf-8")
        print(payload)
        return 0 if rc == 0 else rc


if __name__ == "__main__":
    raise SystemExit(main())
