#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/../../gateway-rust"

PRESET="${PRESET:-normal}"
case "${PRESET}" in
  normal)
    DEFAULT_INITIAL=300
    DEFAULT_MIN=64
    DEFAULT_CAP=1024
    DEFAULT_ALPHA=0.8
    DEFAULT_TICK_MS=200
    DEFAULT_SLEW_RATIO=0.25
    DEFAULT_AUDIT_BATCH=128
    DEFAULT_AUDIT_WAIT_US=200
    ;;
  degraded)
    DEFAULT_INITIAL=300
    DEFAULT_MIN=64
    DEFAULT_CAP=512
    DEFAULT_ALPHA=0.8
    DEFAULT_TICK_MS=200
    DEFAULT_SLEW_RATIO=0.25
    DEFAULT_AUDIT_BATCH=1
    DEFAULT_AUDIT_WAIT_US=5000
    ;;
  *)
    echo "Unknown PRESET: ${PRESET} (use normal|degraded)" >&2
    exit 1
    ;;
esac

BACKPRESSURE_INFLIGHT_DYNAMIC="${BACKPRESSURE_INFLIGHT_DYNAMIC:-1}" \
BACKPRESSURE_INFLIGHT_TARGET_WAL_AGE_SEC="${BACKPRESSURE_INFLIGHT_TARGET_WAL_AGE_SEC:-1.0}" \
BACKPRESSURE_INFLIGHT_ALPHA="${BACKPRESSURE_INFLIGHT_ALPHA:-${DEFAULT_ALPHA}}" \
BACKPRESSURE_INFLIGHT_BETA="${BACKPRESSURE_INFLIGHT_BETA:-0.2}" \
BACKPRESSURE_INFLIGHT_MIN="${BACKPRESSURE_INFLIGHT_MIN:-${DEFAULT_MIN}}" \
BACKPRESSURE_INFLIGHT_CAP="${BACKPRESSURE_INFLIGHT_CAP:-${DEFAULT_CAP}}" \
BACKPRESSURE_INFLIGHT_TICK_MS="${BACKPRESSURE_INFLIGHT_TICK_MS:-${DEFAULT_TICK_MS}}" \
BACKPRESSURE_INFLIGHT_SLEW_RATIO="${BACKPRESSURE_INFLIGHT_SLEW_RATIO:-${DEFAULT_SLEW_RATIO}}" \
BACKPRESSURE_INFLIGHT_HYSTERESIS_OFF_RATIO="${BACKPRESSURE_INFLIGHT_HYSTERESIS_OFF_RATIO:-0.9}" \
BACKPRESSURE_INFLIGHT_INITIAL="${BACKPRESSURE_INFLIGHT_INITIAL:-${DEFAULT_INITIAL}}" \
GATEWAY_PORT="${GATEWAY_PORT:-8082}" \
GATEWAY_TCP_PORT="${GATEWAY_TCP_PORT:-0}" \
AUDIT_ASYNC_WAL="${AUDIT_ASYNC_WAL:-1}" \
AUDIT_FDATASYNC="${AUDIT_FDATASYNC:-1}" \
AUDIT_FDATASYNC_MAX_WAIT_US="${AUDIT_FDATASYNC_MAX_WAIT_US:-${DEFAULT_AUDIT_WAIT_US}}" \
AUDIT_FDATASYNC_MAX_BATCH="${AUDIT_FDATASYNC_MAX_BATCH:-${DEFAULT_AUDIT_BATCH}}" \
JWT_HS256_SECRET="${JWT_HS256_SECRET:-secret123}" \
cargo run --bin gateway-rust
